language: android
sudo: false
jdk:
- oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-29.0.3
  - build-tools-30.0.3
  - android-30
  - android-29
  - android-28
  - android-27
  - android-26
  - android-25
  - android-23
  - android-22
  - android-24
  - extra-android-m2repository
  - extra-google-google_play_services
  - extra-google-m2repository
  - extra-android-m2repository
  - sys-img-armeabi-v7a-android-22
  - extra-android-support
before_install:
  - openssl aes-256-cbc -K $encrypted_b4da38d765e0_key -iv $encrypted_b4da38d765e0_iv -in app.tar.enc -out app.tar -d
  - tar xvf app.tar
script:
- "./gradlew ktlint --no-daemon testHnqisDebugUnitTest"
notifications:
  slack:
    secure: V8Wxde5RTNbNiOzulv6idvMpbWtjVc4DPwApjAgfDI01OD6nLkuogr/z3qqyKbA/uwWnzu5g7+vegFtSdjW1z32kiIO0bO2c0m2L/E542D1/zmWT9N0IPghQIZ+9BAj1ZrgG286tiX85lSV8uLy0r9bAefPWlbdrHhirYi3cTsI=
  email: true
cache:
  directories:
  - "$HOME/.m2"
  - "$HOME/.gradle"

